swagger: '2.0'
info:
  version: '1.0'
  title: GeoNode API Demo
  description: >-
    ### Notes:


    This OAS2 (Swagger 2) specification defines common models and responses,
    that other specifications may reference.


    For example, check out the user poperty in the main.oas2 dataset-partial
    model - it references the dataset model in this specification!


    Likewise, the main.oas2 operations reference the shared error responses in
    this common specification.
  contact:
    name: GeoNode Development Team
    url: 'http://geonode.org'
  license:
    name: GPL-3.0
host: geonode.org
securityDefinitions: {}
paths: {}
responses:
  '401':
    description: ''
    schema:
      $ref: '#/definitions/error-response'
    examples:
      application/json:
        status: '401'
        error: Not Authorized
  '403':
    description: ''
    schema:
      $ref: '#/definitions/error-response'
    examples:
      application/json:
        status: '403'
        error: Forbbiden
  '404':
    description: ''
    schema:
      $ref: '#/definitions/error-response'
    examples:
      application/json:
        status: '404'
        error: Not Found
  '500':
    description: ''
    schema:
      $ref: '#/definitions/error-response'
    examples:
      application/json:
        status: '500'
        error: Server Error
definitions:
  error-response:
    type: object
    title: Error Response
    properties:
      status:
        type: string
      error:
        type: string
    required:
      - status
      - error
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
