default_context:
  project_name: 'geonode-api'
  project_slug: 'geonode-api'
  domain_main: 'api.geonode.org'
  domain_staging: 'demo.api.geonode.org'
  docker_swarm_stack_name_main: 'api-geonode-org'
  docker_swarm_stack_name_staging: 'demo-api-geonode-org'
  secret_key: 'changethis'
  first_superuser: 'admin@api.geonode.org'
  first_superuser_password: 'changethis'
  backend_cors_origins: 'http://localhost, http://localhost:4200, http://localhost:3000, http://localhost:8080, https://localhost, https://localhost:4200, https://localhost:3000, https://localhost:8080, http://dev.api.geonode.org, https://demo.api.geonode.org, https://api.geonode.org, http://local.dockertoolbox.tiangolo.com, http://localhost.tiangolo.com'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@api.geonode.org'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@api.geonode.org'
  pgadmin_default_user_password: 'changethis'
  traefik_constraint_tag: 'api.geonode.org'
  traefik_constraint_tag_staging: 'demo.api.geonode.org'
  traefik_public_network: 'traefik-public'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:changethis'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
