"""Add Process model schema

Revision ID: 5efb633ea595
Revises: d4867f3a4c0a
Create Date: 2019-06-04 10:48:56.729652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5efb633ea595'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process',
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('jobControlOptions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outputTransmission', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_process_description'), 'process', ['description'], unique=False)
    op.create_index(op.f('ix_process_id'), 'process', ['id'], unique=True)
    op.create_index(op.f('ix_process_pid'), 'process', ['pid'], unique=False)
    op.create_index(op.f('ix_process_title'), 'process', ['title'], unique=False)
    op.create_index(op.f('ix_process_version'), 'process', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_process_version'), table_name='process')
    op.drop_index(op.f('ix_process_title'), table_name='process')
    op.drop_index(op.f('ix_process_pid'), table_name='process')
    op.drop_index(op.f('ix_process_id'), table_name='process')
    op.drop_index(op.f('ix_process_description'), table_name='process')
    op.drop_table('process')
    # ### end Alembic commands ###
