"""Remove Item model

Revision ID: a3e99b044b28
Revises: 82cfcfd883ab
Create Date: 2019-06-18 09:45:21.440846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3e99b044b28'
down_revision = '82cfcfd883ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
